# Site settings
title: Jingjie Li (李竞捷)
general_email: jingjieli@outlook.com
academic_email: jingjie.li@wisc.edu

description: > # this means to ignore newlines until "baseurl:"
  Jingjie's personal homepage

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://jingjieli95.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
# github_username: github_username
linkedin_username: linkedin_username
scholar_username: scholar_username
# facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
